spring:
  profiles:
    active:
    - dev

---
spring:
  profiles: dev #开发环境
  application:
    name: microservicecloud-config-jhh-dev

---
spring:
  profiles: test # 测试环境
  application:
    name: microservicecloud-config-jhh-test
    
# 保存为utf-8格式

